[book]
authors = ["Ruoqing He"]
language = "en"
multilingual = false
src = "src"
title = "Track of TimePrinciple"

[output.html]
git-repository-url = "https://github.com/TimePrinciple/timeprinciple.github.io"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/TimePrinciple/timeprinciple.github.io/edit/main/{path}"
